# Change these first
owner: kristoffeys # Your GitHub organization or username, where this repository lives
repo: status-versluys # The name of this repository

sites:
  - name: Groep Versluys
    url: https://groepversluys.be/
  - name: Oosteroever
    url: https://oosteroever.be/
  - name: Ensor Tower
    url: https://www.ensortower.be/.well-known/test.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-versluys
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Groep Versluys
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
